# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

f_cover_pcccd <- function(cover, thresh, M, dist_main2main, dist_main2other) {
    .Call(`_rcccd_f_cover_pcccd`, cover, thresh, M, dist_main2main, dist_main2other)
}

f_cover_rwcccd <- function(dist_main2all, dist_main2main, w, proportion, m, p) {
    .Call(`_rcccd_f_cover_rwcccd`, dist_main2all, dist_main2main, w, proportion, m, p)
}

